### ISSUE TITLE
python venv clarification

### ISSUE THREAD

**Issue by agentdave** [omxhealth/drugbank-sample-apps#10]
People using python all the time may not need this (and probably have their own methods anyway for dealing with other environments), but for the ones that don't, it might be helpful to actually show the creation of an environment here:

https://github.com/omxhealth/drugbank-sample-apps#setting-up-the-virtual-environment

And then use that, instead of `env` as the placeholder in subsequent commands.

**Comment by petreman** [comment]
Yeah I just realized how much I messed up this part, oops. Thanks for bringing it to my attention, it should be better now.
