### ISSUE TITLE
Safari layout issues

### ISSUE THREAD

**Issue by agentdave** [omxhealth/drugbank-sample-apps#9]
Seems to work fine in Chrome, but I noticed in Safari, when you don't have the window tall enough, some of the content doesn't show (and you can't scroll to it):

![Screen Shot 2020-08-14 at 1 46 39 PM](https://user-images.githubusercontent.com/254011/90290450-239ab680-de3b-11ea-86d5-ce66cdb5fa4f.png)

And in the interactions search, the reset button can obscure the content:

![Screen Shot 2020-08-14 at 2 07 58 PM](https://user-images.githubusercontent.com/254011/90290478-357c5980-de3b-11ea-80d0-9fccde45c6ad.png)

**Comment by yourpalal** [comment]
Looks like the interactions reset button issue is still there: 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/763936/90792627-b07cbe80-e2d8-11ea-80fa-3f140a0012af.png">

the data table is can be covered by the reset button, and it doesn't have a scrollbar or anything. 

if I manually hide the reset button, the issue still exists: the results don't get enough space.

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/763936/90793200-6d6f1b00-e2d9-11ea-95c8-72f1bb5de88f.png">

looks like the stuff below the results box is all sticky and sticks over top of the results.
